/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/procaddress/ProcAddressEmitter.java on Fri Oct 09 06:31:53 CEST 2015 ----! */

package jogamp.openal;

import java.io.UnsupportedEncodingException;
import java.util.*;
import com.jogamp.openal.*;
import jogamp.openal.*;
import java.security.AccessController;
import java.security.PrivilegedAction;
import com.jogamp.gluegen.runtime.ProcAddressTable;
import com.jogamp.common.util.SecurityUtil;

/**
 * This table is a cache of pointers to the dynamically-linkable C library.
 * @see ProcAddressTable
 */
public final class ALExtProcAddressTable extends ProcAddressTable {


  public ALExtProcAddressTable(){ super(); }

  public ALExtProcAddressTable(com.jogamp.gluegen.runtime.FunctionAddressResolver resolver){ super(resolver); }

  /* pp */ long _addressof_alcGetProcAddress;
  /* pp */ long _addressof_alGetProcAddress;
  /* pp */ long _addressof_alBufferDataStatic;
  /* pp */ long _addressof_alGenEffects;
  /* pp */ long _addressof_alDeleteEffects;
  /* pp */ long _addressof_alIsEffect;
  /* pp */ long _addressof_alEffecti;
  /* pp */ long _addressof_alEffectiv;
  /* pp */ long _addressof_alEffectf;
  /* pp */ long _addressof_alEffectfv;
  /* pp */ long _addressof_alGetEffecti;
  /* pp */ long _addressof_alGetEffectiv;
  /* pp */ long _addressof_alGetEffectf;
  /* pp */ long _addressof_alGetEffectfv;
  /* pp */ long _addressof_alGenFilters;
  /* pp */ long _addressof_alDeleteFilters;
  /* pp */ long _addressof_alIsFilter;
  /* pp */ long _addressof_alFilteri;
  /* pp */ long _addressof_alFilteriv;
  /* pp */ long _addressof_alFilterf;
  /* pp */ long _addressof_alFilterfv;
  /* pp */ long _addressof_alGetFilteri;
  /* pp */ long _addressof_alGetFilteriv;
  /* pp */ long _addressof_alGetFilterf;
  /* pp */ long _addressof_alGetFilterfv;
  /* pp */ long _addressof_alGenAuxiliaryEffectSlots;
  /* pp */ long _addressof_alDeleteAuxiliaryEffectSlots;
  /* pp */ long _addressof_alIsAuxiliaryEffectSlot;
  /* pp */ long _addressof_alAuxiliaryEffectSloti;
  /* pp */ long _addressof_alAuxiliaryEffectSlotiv;
  /* pp */ long _addressof_alAuxiliaryEffectSlotf;
  /* pp */ long _addressof_alAuxiliaryEffectSlotfv;
  /* pp */ long _addressof_alGetAuxiliaryEffectSloti;
  /* pp */ long _addressof_alGetAuxiliaryEffectSlotiv;
  /* pp */ long _addressof_alGetAuxiliaryEffectSlotf;
  /* pp */ long _addressof_alGetAuxiliaryEffectSlotfv;
  /* pp */ long _addressof_alcSetThreadContext;
  /* pp */ long _addressof_alcGetThreadContext;
  /* pp */ long _addressof_alBufferSubDataSOFT;
  /* pp */ long _addressof_alBufferSamplesSOFT;
  /* pp */ long _addressof_alBufferSubSamplesSOFT;
  /* pp */ long _addressof_alGetBufferSamplesSOFT;
  /* pp */ long _addressof_alIsBufferFormatSupportedSOFT;
  /* pp */ long _addressof_alcLoopbackOpenDeviceSOFT;
  /* pp */ long _addressof_alcIsRenderFormatSupportedSOFT;
  /* pp */ long _addressof_alcRenderSamplesSOFT;
  /* pp */ long _addressof_alSourcedSOFT;
  /* pp */ long _addressof_alSource3dSOFT;
  /* pp */ long _addressof_alSourcedvSOFT;
  /* pp */ long _addressof_alGetSourcedSOFT;
  /* pp */ long _addressof_alGetSource3dSOFT;
  /* pp */ long _addressof_alGetSourcedvSOFT;
  /* pp */ long _addressof_alSourcei64SOFT;
  /* pp */ long _addressof_alSource3i64SOFT;
  /* pp */ long _addressof_alSourcei64vSOFT;
  /* pp */ long _addressof_alGetSourcei64SOFT;
  /* pp */ long _addressof_alGetSource3i64SOFT;
  /* pp */ long _addressof_alGetSourcei64vSOFT;
} // end of class ALExtProcAddressTable
