/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/procaddress/ProcAddressEmitter.java on Fri Oct 09 06:31:35 CEST 2015 ----! */

package jogamp.openal;

import com.jogamp.openal.*;
import jogamp.openal.*;
import java.security.AccessController;
import java.security.PrivilegedAction;
import com.jogamp.gluegen.runtime.ProcAddressTable;
import com.jogamp.common.util.SecurityUtil;

/**
 * This table is a cache of pointers to the dynamically-linkable C library.
 * @see ProcAddressTable
 */
public final class ALProcAddressTable extends ProcAddressTable {


  public ALProcAddressTable(){ super(); }

  public ALProcAddressTable(com.jogamp.gluegen.runtime.FunctionAddressResolver resolver){ super(resolver); }

  /* pp */ long _addressof_alDopplerFactor;
  /* pp */ long _addressof_alDopplerVelocity;
  /* pp */ long _addressof_alSpeedOfSound;
  /* pp */ long _addressof_alDistanceModel;
  /* pp */ long _addressof_alEnable;
  /* pp */ long _addressof_alDisable;
  /* pp */ long _addressof_alIsEnabled;
  /* pp */ long _addressof_alGetString;
  /* pp */ long _addressof_alGetBooleanv;
  /* pp */ long _addressof_alGetIntegerv;
  /* pp */ long _addressof_alGetFloatv;
  /* pp */ long _addressof_alGetDoublev;
  /* pp */ long _addressof_alGetBoolean;
  /* pp */ long _addressof_alGetInteger;
  /* pp */ long _addressof_alGetFloat;
  /* pp */ long _addressof_alGetDouble;
  /* pp */ long _addressof_alGetError;
  /* pp */ long _addressof_alIsExtensionPresent;
  /* pp */ long _addressof_alGetProcAddress;
  /* pp */ long _addressof_alGetEnumValue;
  /* pp */ long _addressof_alListenerf;
  /* pp */ long _addressof_alListener3f;
  /* pp */ long _addressof_alListenerfv;
  /* pp */ long _addressof_alListeneri;
  /* pp */ long _addressof_alListener3i;
  /* pp */ long _addressof_alListeneriv;
  /* pp */ long _addressof_alGetListenerf;
  /* pp */ long _addressof_alGetListener3f;
  /* pp */ long _addressof_alGetListenerfv;
  /* pp */ long _addressof_alGetListeneri;
  /* pp */ long _addressof_alGetListener3i;
  /* pp */ long _addressof_alGetListeneriv;
  /* pp */ long _addressof_alGenSources;
  /* pp */ long _addressof_alDeleteSources;
  /* pp */ long _addressof_alIsSource;
  /* pp */ long _addressof_alSourcef;
  /* pp */ long _addressof_alSource3f;
  /* pp */ long _addressof_alSourcefv;
  /* pp */ long _addressof_alSourcei;
  /* pp */ long _addressof_alSource3i;
  /* pp */ long _addressof_alSourceiv;
  /* pp */ long _addressof_alGetSourcef;
  /* pp */ long _addressof_alGetSource3f;
  /* pp */ long _addressof_alGetSourcefv;
  /* pp */ long _addressof_alGetSourcei;
  /* pp */ long _addressof_alGetSource3i;
  /* pp */ long _addressof_alGetSourceiv;
  /* pp */ long _addressof_alSourcePlayv;
  /* pp */ long _addressof_alSourceStopv;
  /* pp */ long _addressof_alSourceRewindv;
  /* pp */ long _addressof_alSourcePausev;
  /* pp */ long _addressof_alSourcePlay;
  /* pp */ long _addressof_alSourceStop;
  /* pp */ long _addressof_alSourceRewind;
  /* pp */ long _addressof_alSourcePause;
  /* pp */ long _addressof_alSourceQueueBuffers;
  /* pp */ long _addressof_alSourceUnqueueBuffers;
  /* pp */ long _addressof_alGenBuffers;
  /* pp */ long _addressof_alDeleteBuffers;
  /* pp */ long _addressof_alIsBuffer;
  /* pp */ long _addressof_alBufferData;
  /* pp */ long _addressof_alBufferf;
  /* pp */ long _addressof_alBuffer3f;
  /* pp */ long _addressof_alBufferfv;
  /* pp */ long _addressof_alBufferi;
  /* pp */ long _addressof_alBuffer3i;
  /* pp */ long _addressof_alBufferiv;
  /* pp */ long _addressof_alGetBufferf;
  /* pp */ long _addressof_alGetBuffer3f;
  /* pp */ long _addressof_alGetBufferfv;
  /* pp */ long _addressof_alGetBufferi;
  /* pp */ long _addressof_alGetBuffer3i;
  /* pp */ long _addressof_alGetBufferiv;
} // end of class ALProcAddressTable
