/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Oct 09 06:31:46 CEST 2015 ----! */

package com.jogamp.openal;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;

public interface ALCConstants {

  /** CType: int */
  public static final int ALC_DEVICE_SPECIFIER = 0x1005;
  /** CType: int */
  public static final int ALC_CAPTURE_SAMPLES = 0x312;
  /** CType: int */
  public static final int ALC_NO_ERROR = 0x0;
  /** CType: int */
  public static final int ALC_ALL_ATTRIBUTES = 0x1003;
  /** CType: int */
  public static final int ALC_EXT_CAPTURE = 0x1;
  /** CType: int */
  public static final int ALC_OUT_OF_MEMORY = 0xa005;
  /** CType: int */
  public static final int ALC_CAPTURE_DEVICE_SPECIFIER = 0x310;
  /** CType: int */
  public static final int ALC_MINOR_VERSION = 0x1001;
  /** CType: int */
  public static final int ALC_TRUE = 0x1;
  /** CType: int */
  public static final int ALC_ENUMERATE_ALL_EXT = 0x1;
  /** CType: int */
  public static final int ALC_INVALID_ENUM = 0xa003;
  /** CType: int */
  public static final int ALC_MONO_SOURCES = 0x1010;
  /** CType: int */
  public static final int ALC_EXTENSIONS = 0x1006;
  /** CType: int */
  public static final int ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER = 0x311;
  /** CType: int */
  public static final int ALC_REFRESH = 0x1008;
  /** CType: int */
  public static final int ALC_INVALID_CONTEXT = 0xa002;
  /** CType: int */
  public static final int ALC_INVALID = 0x0;
  /** CType: int */
  public static final int ALC_STEREO_SOURCES = 0x1011;
  /** CType: int */
  public static final int ALC_INVALID_VALUE = 0xa004;
  /** CType: int */
  public static final int ALC_MAJOR_VERSION = 0x1000;
  /** CType: int */
  public static final int ALC_DEFAULT_ALL_DEVICES_SPECIFIER = 0x1012;
  /** CType: int */
  public static final int ALC_VERSION_0_1 = 0x1;
  /** CType: int */
  public static final int ALC_ALL_DEVICES_SPECIFIER = 0x1013;
  /** CType: int */
  public static final int ALC_FALSE = 0x0;
  /** CType: int */
  public static final int ALC_DEFAULT_DEVICE_SPECIFIER = 0x1004;
  /** CType: int */
  public static final int ALC_INVALID_DEVICE = 0xa001;
  /** CType: int */
  public static final int ALC_FREQUENCY = 0x1007;
  /** CType: int */
  public static final int ALC_SYNC = 0x1009;
  /** CType: int */
  public static final int ALC_ATTRIBUTES_SIZE = 0x1002;


} // end of class ALCConstants
