/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Oct 09 06:31:39 CEST 2015 ----! */

package com.jogamp.openal;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;

public interface ALConstants {

  /** CType: int */
  public static final int AL_ILLEGAL_COMMAND = 0xa004;
  /** CType: int */
  public static final int AL_PROCESSED = 0x2012;
  /** CType: int */
  public static final int AL_FREQUENCY = 0x2001;
  /** CType: int */
  public static final int AL_NO_ERROR = 0x0;
  /** CType: int */
  public static final int AL_VENDOR = 0xb001;
  /** CType: int */
  public static final int AL_STATIC = 0x1028;
  /** CType: int */
  public static final int AL_INVALID_ENUM = 0xa002;
  /** CType: int */
  public static final int AL_MAX_DISTANCE = 0x1023;
  /** CType: int */
  public static final int AL_ROLLOFF_FACTOR = 0x1021;
  /** CType: int */
  public static final int AL_GAIN = 0x100a;
  /** CType: int */
  public static final int AL_SIZE = 0x2004;
  /** CType: int */
  public static final int AL_DISTANCE_MODEL = 0xd000;
  /** CType: int */
  public static final int AL_BYTE_OFFSET = 0x1026;
  /** CType: int */
  public static final int AL_SOURCE_STATE = 0x1010;
  /** CType: int */
  public static final int AL_STOPPED = 0x1014;
  /** CType: int */
  public static final int AL_REFERENCE_DISTANCE = 0x1020;
  /** CType: int */
  public static final int AL_MIN_GAIN = 0x100d;
  /** CType: int */
  public static final int AL_PLAYING = 0x1012;
  /** CType: int */
  public static final int AL_INVERSE_DISTANCE_CLAMPED = 0xd002;
  /** CType: int */
  public static final int AL_PITCH = 0x1003;
  /** CType: int */
  public static final int AL_OUT_OF_MEMORY = 0xa005;
  /** CType: int */
  public static final int AL_FORMAT_MONO8 = 0x1100;
  /** CType: int */
  public static final int AL_TRUE = 0x1;
  /** CType: int */
  public static final int AL_LINEAR_DISTANCE = 0xd003;
  /** CType: int */
  public static final int AL_LOOPING = 0x1007;
  /** CType: int */
  public static final int AL_STREAMING = 0x1029;
  /** CType: int */
  public static final int AL_EXPONENT_DISTANCE_CLAMPED = 0xd006;
  /** CType: int */
  public static final int AL_CHANNELS = 0x2003;
  /** CType: int */
  public static final int AL_PAUSED = 0x1013;
  /** CType: int */
  public static final int AL_CONE_OUTER_GAIN = 0x1022;
  /** CType: int */
  public static final int AL_INVERSE_DISTANCE = 0xd001;
  /** CType: int */
  public static final int AL_ILLEGAL_ENUM = 0xa002;
  /** CType: int */
  public static final int AL_DIRECTION = 0x1005;
  /** CType: int */
  public static final int AL_INVALID_OPERATION = 0xa004;
  /** CType: int */
  public static final int AL_ORIENTATION = 0x100f;
  /** CType: int */
  public static final int AL_FORMAT_STEREO8 = 0x1102;
  /** CType: int */
  public static final int AL_CONE_OUTER_ANGLE = 0x1002;
  /** CType: int */
  public static final int AL_DOPPLER_VELOCITY = 0xc001;
  /** CType: int */
  public static final int AL_RENDERER = 0xb003;
  /** CType: int */
  public static final int AL_SAMPLE_OFFSET = 0x1025;
  /** CType: int */
  public static final int AL_FORMAT_STEREO16 = 0x1103;
  /** CType: int */
  public static final int AL_SEC_OFFSET = 0x1024;
  /** CType: int */
  public static final int AL_POSITION = 0x1004;
  /** CType: int */
  public static final int AL_PENDING = 0x2011;
  /** CType: int */
  public static final int AL_UNUSED = 0x2010;
  /** CType: int */
  public static final int AL_INVALID_VALUE = 0xa003;
  /** CType: int */
  public static final int AL_NONE = 0x0;
  /** CType: int */
  public static final int AL_BUFFER = 0x1009;
  /** CType: int */
  public static final int AL_BUFFERS_PROCESSED = 0x1016;
  /** CType: int */
  public static final int AL_VELOCITY = 0x1006;
  /** CType: int */
  public static final int AL_DOPPLER_FACTOR = 0xc000;
  /** CType: int */
  public static final int AL_MAX_GAIN = 0x100e;
  /** CType: int */
  public static final int AL_SPEED_OF_SOUND = 0xc003;
  /** CType: int */
  public static final int AL_UNDETERMINED = 0x1030;
  /** CType: int */
  public static final int AL_EXTENSIONS = 0xb004;
  /** CType: int */
  public static final int AL_EXPONENT_DISTANCE = 0xd005;
  /** CType: int */
  public static final int AL_INVALID = ( - 0x1 );
  /** CType: int */
  public static final int AL_VERSION = 0xb002;
  /** CType: int */
  public static final int AL_INITIAL = 0x1011;
  /** CType: int */
  public static final int AL_BUFFERS_QUEUED = 0x1015;
  /** CType: int */
  public static final int AL_BITS = 0x2002;
  /** CType: int */
  public static final int AL_CONE_INNER_ANGLE = 0x1001;
  /** CType: int */
  public static final int AL_SOURCE_RELATIVE = 0x202;
  /** CType: int */
  public static final int AL_SOURCE_TYPE = 0x1027;
  /** CType: int */
  public static final int AL_LINEAR_DISTANCE_CLAMPED = 0xd004;
  /** CType: int */
  public static final int AL_FORMAT_MONO16 = 0x1101;
  /** CType: int */
  public static final int AL_FALSE = 0x0;
  /** CType: int */
  public static final int AL_INVALID_NAME = 0xa001;


} // end of class ALConstants
