/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Oct 09 06:32:02 CEST 2015 ----! */

package com.jogamp.openal;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;

public interface ALExtConstants {

  /** CType: float */
  public static final float AL_FLANGER_MAX_FEEDBACK = ( 1.0f );
  /** CType: int */
  public static final int AL_7POINT1_8_SOFT = 0x1210;
  /** CType: float */
  public static final float AL_RING_MODULATOR_MAX_FREQUENCY = ( 8000.0f );
  /** CType: int */
  public static final int AL_FILTER_LAST_PARAMETER = 0x8000;
  /** CType: int */
  public static final int AL_SAMPLE_RW_OFFSETS_SOFT = 0x1032;
  /** CType: int */
  public static final int AL_EFFECT_FREQUENCY_SHIFTER = 0x6;
  /** CType: int */
  public static final int AL_REVERB_DIFFUSION = 0x2;
  /** CType: double */
  public static final double AL_RING_MODULATOR_MIN_HIGHPASS_CUTOFF = ( 0.0 );
  /** CType: int */
  public static final int AL_CHORUS_MAX_PHASE = ( 0xb4 );
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_MID1_WIDTH = ( 0.01f );
  /** CType: int */
  public static final int AL_EFFECT_EQUALIZER = 0xc;
  /** CType: int */
  public static final int AL_EXT_SOURCE_RADIUS = 0x1;
  /** CType: int */
  public static final int AL_EXT_double = 0x1;
  /** CType: int */
  public static final int AL_COMPRESSOR_DEFAULT_ONOFF = ( 0x1 );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_GAIN = ( 0.32f );
  /** CType: int */
  public static final int AL_RING_MODULATOR_SAWTOOTH = ( 0x1 );
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_LATE_REVERB_DELAY = ( 0.011f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_WAVEFORM = 0x5;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MAX_PHONEMEA_COARSE_TUNING = ( 0x18 );
  /** CType: int */
  public static final int AL_MONO16_SOFT = 0x1101;
  /** CType: int */
  public static final int AL_EAXREVERB_LATE_REVERB_GAIN = 0xc;
  /** CType: int */
  public static final int AL_COMPRESSOR_ONOFF = 0x1;
  /** CType: int */
  public static final int AL_EQUALIZER_MID2_CENTER = 0x7;
  /** CType: int */
  public static final int AL_EXT_float32 = 0x1;
  /** CType: int */
  public static final int AL_HIGHPASS_GAIN = 0x1;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_DECAY_TIME = ( 20.0f );
  /** CType: float */
  public static final float AL_MAX_AIR_ABSORPTION_FACTOR = ( 10.0f );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_REFLECTIONS_DELAY = ( 0.007f );
  /** CType: float */
  public static final float AL_DEFAULT_METERS_PER_UNIT = ( 1.0f );
  /** CType: int */
  public static final int AL_EAXREVERB_MODULATION_DEPTH = 0x12;
  /** CType: int */
  public static final int AL_EFFECT_EAXREVERB = 0x8000;
  /** CType: int */
  public static final int AL_REVERB_ROOM_ROLLOFF_FACTOR = 0xc;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_GAINLF = ( 0.0 );
  /** CType: float */
  public static final float AL_FLANGER_MAX_RATE = ( 10.0f );
  /** CType: float */
  public static final float AL_MAX_ROOM_ROLLOFF_FACTOR = ( 10.0f );
  /** CType: int */
  public static final int AL_SEC_LENGTH_SOFT = 0x200b;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_MODULATION_DEPTH = ( 1.0f );
  /** CType: int */
  public static final int AL_EAXREVERB_ECHO_TIME = 0xf;
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_MIN_RIGHT_DIRECTION = ( 0x0 );
  /** CType: float */
  public static final float AL_REVERB_MAX_GAINHF = ( 1.0f );
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_DEFAULT_RIGHT_DIRECTION = ( 0x0 );
  /** CType: int */
  public static final int AL_EAXREVERB_DENSITY = 0x1;
  /** CType: int */
  public static final int AL_EFFECTSLOT_GAIN = 0x2;
  /** CType: int */
  public static final int AL_MONO32F_SOFT = 0x10010;
  /** CType: int */
  public static final int AL_FORMAT_61CHN32 = 0x120f;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_DECAY_HFRATIO = ( 0.83f );
  /** CType: int */
  public static final int AL_EAXREVERB_DEFAULT_DECAY_HFLIMIT = 0x1;
  /** CType: int */
  public static final int AL_SOFT_loop_points = 0x1;
  /** CType: int */
  public static final int AL_CHORUS_WAVEFORM_TRIANGLE = ( 0x1 );
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_AIR_ABSORPTION_GAINHF = ( 0.892f );
  /** CType: int */
  public static final int AL_FORMAT_WAVE_EXT = 0x10002;
  /** CType: int */
  public static final int AL_EQUALIZER_MID2_GAIN = 0x6;
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_LFREFERENCE = ( 20.0f );
  /** CType: int */
  public static final int AL_MONO_SOFT = 0x1500;
  /** CType: int */
  public static final int AL_AIR_ABSORPTION_FACTOR = 0x20007;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_LATE_REVERB_GAIN = ( 10.0f );
  /** CType: int */
  public static final int AL_RING_MODULATOR_SINUSOID = ( 0x0 );
  /** CType: int */
  public static final int AL_EFFECT_FIRST_PARAMETER = 0x0;
  /** CType: int */
  public static final int ALC_SOFT_loopback = 0x1;
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_DEFAULT_COARSE_TUNE = ( 0xc );
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_MAX_FINE_TUNE = ( 0x32 );
  /** CType: int */
  public static final int AL_EAXREVERB_ECHO_DEPTH = 0x10;
  /** CType: float */
  public static final float AL_ECHO_MAX_DAMPING = ( 0.99f );
  /** CType: float */
  public static final float AL_MAX_CONE_OUTER_GAINHF = ( 1.0f );
  /** CType: int */
  public static final int AL_FORMAT_IMA_ADPCM_MONO16_EXT = 0x10000;
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_HIGH_CUTOFF = ( 16000.0f );
  /** CType: int */
  public static final int ALC_QUAD_SOFT = 0x1503;
  /** CType: int */
  public static final int AL_SEC_OFFSET_LATENCY_SOFT = 0x1201;
  /** CType: int */
  public static final int AL_REVERB_DENSITY = 0x1;
  /** CType: int */
  public static final int AL_METERS_PER_UNIT = 0x20004;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_LATE_REVERB_DELAY = ( 0.1f );
  /** CType: double */
  public static final double AL_MIN_ROOM_ROLLOFF_FACTOR = ( 0.0 );
  /** CType: float */
  public static final float AL_BANDPASS_MAX_GAINLF = ( 1.0f );
  /** CType: float */
  public static final float AL_REVERB_MIN_DECAY_TIME = ( 0.1f );
  /** CType: float */
  public static final float AL_DISTORTION_MAX_EQBANDWIDTH = ( 24000.0f );
  /** CType: int */
  public static final int AL_DEFAULT_DIRECT_FILTER_GAINHF_AUTO = 0x1;
  /** CType: int */
  public static final int AL_EAXREVERB_AIR_ABSORPTION_GAINHF = 0x13;
  /** CType: float */
  public static final float AL_FLANGER_MAX_DEPTH = ( 1.0f );
  /** CType: int */
  public static final int AL_EFFECT_DEDICATED_LOW_FREQUENCY_EFFECT = 0x9000;
  /** CType: float */
  public static final float AL_DISTORTION_MIN_LOWPASS_CUTOFF = ( 80.0f );
  /** CType: int */
  public static final int AL_REAR16_SOFT = 0x1208;
  /** CType: int */
  public static final int AL_EFFECT_COMPRESSOR = 0xb;
  /** CType: float */
  public static final float AL_AUTOWAH_MAX_ATTACK_TIME = ( 1.0f );
  /** CType: int */
  public static final int AL_FORMAT_REAR8 = 0x1207;
  /** CType: float */
  public static final float AL_AUTOWAH_MIN_PEAK_GAIN = ( 3.0E-5f );
  /** CType: int */
  public static final int AL_FORMAT_STEREO_FLOAT32 = 0x10011;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_GAINHF = ( 0.89f );
  /** CType: int */
  public static final int AL_REVERB_GAINHF = 0x4;
  /** CType: float */
  public static final float AL_DISTORTION_MAX_EDGE = ( 1.0f );
  /** CType: float */
  public static final float AL_CHORUS_DEFAULT_RATE = ( 1.1f );
  /** CType: float */
  public static final float AL_DISTORTION_DEFAULT_GAIN = ( 0.05f );
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_DIFFUSION = ( 0.0 );
  /** CType: int */
  public static final int AL_MAX_AUXILIARY_SEND_FILTER_GAINHF_AUTO = 0x1;
  /** CType: int */
  public static final int AL_EAXREVERB_DECAY_LFRATIO = 0x8;
  /** CType: float */
  public static final float AL_HIGHPASS_MAX_GAINLF = ( 1.0f );
  /** CType: int */
  public static final int AL_5POINT1_8_SOFT = 0x120a;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_DEFAULT_PHONEMEB = ( 0xa );
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_MID1_WIDTH = ( 1.0f );
  /** CType: float */
  public static final float AL_FLANGER_DEFAULT_FEEDBACK = ( - 0.5f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_DEFAULT_PHONEMEA = ( 0x0 );
  /** CType: double */
  public static final double AL_FLANGER_MIN_DELAY = ( 0.0 );
  /** CType: double */
  public static final double AL_REVERB_MIN_REFLECTIONS_DELAY = ( 0.0 );
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_MODULATION_TIME = ( 0.04f );
  /** CType: int */
  public static final int AL_EQUALIZER_MID1_WIDTH = 0x5;
  /** CType: float */
  public static final float AL_AUTOWAH_MAX_RESONANCE = ( 1000.0f );
  /** CType: double */
  public static final double AL_FREQUENCY_SHIFTER_MIN_FREQUENCY = ( 0.0 );
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_MID1_GAIN = ( 1.0f );
  /** CType: int */
  public static final int AL_UNSIGNED_INT_SOFT = 0x1405;
  /** CType: double */
  public static final double AL_DEFAULT_AIR_ABSORPTION_FACTOR = ( 0.0 );
  /** CType: double */
  public static final double AL_HIGHPASS_MIN_GAINLF = ( 0.0 );
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_HIGH_CUTOFF = ( 6000.0f );
  /** CType: float */
  public static final float AL_LOWPASS_DEFAULT_GAINHF = ( 1.0f );
  /** CType: int */
  public static final int AL_REVERB_MAX_DECAY_HFLIMIT = 0x1;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MAX_PHONEMEB_COARSE_TUNING = ( 0x18 );
  /** CType: int */
  public static final int AL_LOOP_POINTS_SOFT = 0x2015;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_DIFFUSION = ( 1.0f );
  /** CType: double */
  public static final double AL_MIN_AIR_ABSORPTION_FACTOR = ( 0.0 );
  /** CType: int */
  public static final int AL_EQUALIZER_HIGH_CUTOFF = 0xa;
  /** CType: int */
  public static final int AL_FORMAT_STEREO_DOUBLE_EXT = 0x10013;
  /** CType: float */
  public static final float AL_ECHO_MAX_SPREAD = ( 1.0f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MIN_PHONEMEB = ( 0x0 );
  /** CType: int */
  public static final int AL_SAMPLE_OFFSET_LATENCY_SOFT = 0x1200;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MIN_PHONEMEA = ( 0x0 );
  /** CType: float */
  public static final float AL_CHORUS_MAX_DELAY = ( 0.016f );
  /** CType: int */
  public static final int AL_EAXREVERB_GAIN = 0x3;
  /** CType: int */
  public static final int AL_DIRECT_FILTER_GAINHF_AUTO = 0x2000a;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_GAIN = ( 1.0f );
  /** CType: double */
  public static final double AL_HIGHPASS_MIN_GAIN = ( 0.0 );
  /** CType: int */
  public static final int AL_MAX_AUXILIARY_SEND_FILTER_GAIN_AUTO = 0x1;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_DECAY_LFRATIO = ( 2.0f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_DEFAULT_PHONEMEB_COARSE_TUNING = ( 0x0 );
  /** CType: int */
  public static final int AL_REVERB_LATE_REVERB_GAIN = 0x9;
  /** CType: int */
  public static final int AL_EFFECTSLOT_AUXILIARY_SEND_AUTO = 0x3;
  /** CType: int */
  public static final int AL_UNSIGNED_BYTE_SOFT = 0x1401;
  /** CType: float */
  public static final float AL_ECHO_MAX_LRDELAY = ( 0.404f );
  /** CType: int */
  public static final int AL_FORMAT_MONO_ALAW_EXT = 0x10016;
  /** CType: double */
  public static final double AL_ECHO_MIN_DAMPING = ( 0.0 );
  /** CType: int */
  public static final int AL_CHORUS_MAX_WAVEFORM = ( 0x1 );
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_DEFAULT_LEFT_DIRECTION = ( 0x0 );
  /** CType: int */
  public static final int AL_5POINT1_SOFT = 0x1504;
  /** CType: float */
  public static final float AL_DEFAULT_CONE_OUTER_GAINHF = ( 1.0f );
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_RIGHT_DIRECTION = 0x3;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_REFLECTIONS_GAIN = ( 0.05f );
  /** CType: int */
  public static final int AL_FORMAT_51CHN8 = 0x120a;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_REFLECTIONS_GAIN = ( 0.0 );
  /** CType: int */
  public static final int AL_BYTE_RW_OFFSETS_SOFT = 0x1031;
  /** CType: float */
  public static final float AL_LOWPASS_MAX_GAIN = ( 1.0f );
  /** CType: int */
  public static final int AL_CHORUS_FEEDBACK = 0x5;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_GAIN = ( 0.32f );
  /** CType: int */
  public static final int AL_REVERB_LATE_REVERB_DELAY = 0xa;
  /** CType: int */
  public static final int ALC_LOKI_audio_channel = 0x1;
  /** CType: float */
  public static final float AL_BANDPASS_MAX_GAINHF = ( 1.0f );
  /** CType: float */
  public static final float AL_HIGHPASS_DEFAULT_GAINLF = ( 1.0f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_DEFAULT_PHONEMEA_COARSE_TUNING = ( 0x0 );
  /** CType: float */
  public static final float AL_AUTOWAH_DEFAULT_PEAK_GAIN = ( 11.22f );
  /** CType: int */
  public static final int AL_EXT_STEREO_ANGLES = 0x1;
  /** CType: int */
  public static final int AL_EFFECT_REVERB = 0x1;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MAX_WAVEFORM = ( 0x2 );
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_MID2_GAIN = ( 7.943f );
  /** CType: int */
  public static final int ALC_CHAN_MAIN_LOKI = 0x500001;
  /** CType: int */
  public static final int AL_FORMAT_STEREO_MULAW = 0x10015;
  /** CType: int */
  public static final int AL_FORMAT_STEREO_IMA4 = 0x1301;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_GAIN = ( 0.0 );
  /** CType: int */
  public static final int AL_INTERNAL_FORMAT_SOFT = 0x2008;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_WAVEFORM_SAWTOOTH = ( 0x2 );
  /** CType: int */
  public static final int AL_DOUBLE_SOFT = 0x1407;
  /** CType: int */
  public static final int AL_FILTER_LOWPASS = 0x1;
  /** CType: int */
  public static final int AL_EXT_vorbis = 0x1;
  /** CType: int */
  public static final int AL_FORMAT_61CHN8 = 0x120d;
  /** CType: int */
  public static final int ALC_STEREO_SOFT = 0x1501;
  /** CType: int */
  public static final int AL_LOKI_quadriphonic = 0x1;
  /** CType: float */
  public static final float AL_AUTOWAH_MAX_RELEASE_TIME = ( 1.0f );
  /** CType: int */
  public static final int AL_REVERB_GAIN = 0x3;
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_MAX_COARSE_TUNE = ( 0xc );
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_MID2_CENTER = ( 3000.0f );
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_MID1_WIDTH = ( 1.0f );
  /** CType: int */
  public static final int AL_EQUALIZER_MID1_GAIN = 0x3;
  /** CType: int */
  public static final int AL_CHORUS_WAVEFORM = 0x1;
  /** CType: int */
  public static final int AL_REAR32F_SOFT = 0x1209;
  /** CType: int */
  public static final int AL_CHORUS_MIN_WAVEFORM = ( 0x0 );
  /** CType: int */
  public static final int AL_FORMAT_QUAD32 = 0x1206;
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_DECAY_TIME = ( 0.1f );
  /** CType: int */
  public static final int AL_EXT_MULAW = 0x1;
  /** CType: int */
  public static final int AL_AUTOWAH_ATTACK_TIME = 0x1;
  /** CType: int */
  public static final int AL_STEREO_ANGLES = 0x1030;
  /** CType: int */
  public static final int AL_AUXILIARY_SEND_FILTER_GAINHF_AUTO = 0x2000c;
  /** CType: int */
  public static final int AL_BYTE_SOFT = 0x1400;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_UW = ( 0xe );
  /** CType: int */
  public static final int AL_FLANGER_MIN_PHASE = ( - 0xb4 );
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_MIN_LEFT_DIRECTION = ( 0x0 );
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_ECHO_TIME = ( 0.25f );
  /** CType: double */
  public static final double AL_EAXREVERB_DEFAULT_MODULATION_DEPTH = ( 0.0 );
  /** CType: float */
  public static final float AL_CHORUS_DEFAULT_FEEDBACK = ( 0.25f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_UH = ( 0xd );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_DECAY_LFRATIO = ( 1.0f );
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_MID2_WIDTH = ( 1.0f );
  /** CType: int */
  public static final int AL_7POINT1_16_SOFT = 0x1211;
  /** CType: int */
  public static final int ALC_6POINT1_SOFT = 0x1505;
  /** CType: float */
  public static final float AL_AUTOWAH_MAX_PEAK_GAIN = ( 31621.0f );
  /** CType: int */
  public static final int AL_HIGHPASS_GAINLF = 0x2;
  /** CType: int */
  public static final int AL_EFFECT_DEDICATED_DIALOGUE = 0x9001;
  /** CType: int */
  public static final int AL_AUTOWAH_RELEASE_TIME = 0x2;
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_ECHO_TIME = ( 0.25f );
  /** CType: float */
  public static final float AL_ECHO_MIN_SPREAD = ( - 1.0f );
  /** CType: int */
  public static final int AL_FILTER_HIGHPASS = 0x2;
  /** CType: int */
  public static final int AL_FLANGER_DEPTH = 0x4;
  /** CType: int */
  public static final int AL_EAXREVERB_MODULATION_TIME = 0x11;
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_LFREFERENCE = ( 250.0f );
  /** CType: float */
  public static final float AL_RING_MODULATOR_DEFAULT_HIGHPASS_CUTOFF = ( 800.0f );
  /** CType: int */
  public static final int AL_AUXILIARY_SEND_FILTER_GAIN_AUTO = 0x2000b;
  /** CType: int */
  public static final int AL_EFFECT_NULL = 0x0;
  /** CType: float */
  public static final float AL_BANDPASS_MAX_GAIN = ( 1.0f );
  /** CType: float */
  public static final float AL_DISTORTION_MIN_EQCENTER = ( 80.0f );
  /** CType: int */
  public static final int ALC_EXT_thread_local_context = 0x1;
  /** CType: float */
  public static final float AL_FLANGER_DEFAULT_DEPTH = ( 1.0f );
  /** CType: int */
  public static final int AL_EFFECT_CHORUS = 0x2;
  /** CType: int */
  public static final int AL_FORMAT_IMA_ADPCM_STEREO16_EXT = 0x10001;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_GAINHF = ( 1.0f );
  /** CType: float */
  public static final float AL_FLANGER_DEFAULT_RATE = ( 0.27f );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_REFLECTIONS_GAIN = ( 0.05f );
  /** CType: int */
  public static final int AL_SOURCE_DISTANCE_MODEL = 0x200;
  /** CType: float */
  public static final float AL_BANDPASS_DEFAULT_GAINHF = ( 1.0f );
  /** CType: float */
  public static final float AL_REVERB_MAX_DIFFUSION = ( 1.0f );
  /** CType: double */
  public static final double AL_CHORUS_MIN_DELAY = ( 0.0 );
  /** CType: int */
  public static final int AL_LOWPASS_GAIN = 0x1;
  /** CType: int */
  public static final int AL_STEREO8_SOFT = 0x1102;
  /** CType: int */
  public static final int AL_EQUALIZER_LOW_GAIN = 0x1;
  /** CType: int */
  public static final int AL_5POINT1_32F_SOFT = 0x120c;
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_DIRECTION_DOWN = ( 0x0 );
  /** CType: int */
  public static final int ALC_UNSIGNED_INT_SOFT = 0x1405;
  /** CType: double */
  public static final double AL_FLANGER_MIN_RATE = ( 0.0 );
  /** CType: int */
  public static final int AL_ECHO_LRDELAY = 0x2;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_DENSITY = ( 0.0 );
  /** CType: int */
  public static final int AL_QUAD8_SOFT = 0x1204;
  /** CType: int */
  public static final int ALC_7POINT1_SOFT = 0x1506;
  /** CType: float */
  public static final float AL_DISTORTION_MIN_GAIN = ( 0.01f );
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_MODULATION_TIME = ( 4.0f );
  /** CType: int */
  public static final int AL_6POINT1_16_SOFT = 0x120e;
  /** CType: int */
  public static final int ALC_MONO_SOFT = 0x1500;
  /** CType: int */
  public static final int AL_REVERB_AIR_ABSORPTION_GAINHF = 0xb;
  /** CType: int */
  public static final int AL_REVERB_DECAY_HFRATIO = 0x6;
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_DIRECTION_OFF = ( 0x2 );
  /** CType: float */
  public static final float AL_DISTORTION_DEFAULT_LOWPASS_CUTOFF = ( 8000.0f );
  /** CType: int */
  public static final int AL_EXT_IMA4 = 0x1;
  /** CType: int */
  public static final int AL_BANDPASS_GAIN = 0x1;
  /** CType: int */
  public static final int AL_EXT_MULAW_MCFORMATS = 0x1;
  /** CType: int */
  public static final int AL_REVERB_DECAY_TIME = 0x5;
  /** CType: float */
  public static final float AL_REVERB_MAX_ROOM_ROLLOFF_FACTOR = ( 10.0f );
  /** CType: float */
  public static final float AL_LOWPASS_MAX_GAINHF = ( 1.0f );
  /** CType: double */
  public static final double AL_CHORUS_MIN_RATE = ( 0.0 );
  /** CType: float */
  public static final float AL_AUTOWAH_DEFAULT_ATTACK_TIME = ( 0.06f );
  /** CType: int */
  public static final int ALC_UNSIGNED_SHORT_SOFT = 0x1403;
  /** CType: int */
  public static final int AL_FORMAT_61CHN16 = 0x120e;
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_DIFFUSION = ( 1.0f );
  /** CType: int */
  public static final int AL_MIN_AUXILIARY_SEND_FILTER_GAINHF_AUTO = 0x0;
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_MID2_GAIN = ( 1.0f );
  /** CType: float */
  public static final float AL_REVERB_MAX_DECAY_HFRATIO = ( 2.0f );
  /** CType: double */
  public static final double AL_REVERB_MIN_DENSITY = ( 0.0 );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_GAINLF = ( 1.0f );
  /** CType: int */
  public static final int AL_FILTER_TYPE = 0x8001;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_DECAY_HFRATIO = ( 2.0f );
  /** CType: double */
  public static final double AL_EAXREVERB_DEFAULT_REFLECTIONS_PAN_XYZ = ( 0.0 );
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_LOW_GAIN = ( 1.0f );
  /** CType: int */
  public static final int AL_CHORUS_MIN_PHASE = ( - 0xb4 );
  /** CType: float */
  public static final float AL_VOCAL_MORPHER_MAX_RATE = ( 10.0f );
  /** CType: int */
  public static final int AL_RING_MODULATOR_MIN_WAVEFORM = ( 0x0 );
  /** CType: int */
  public static final int AL_CHORUS_DEPTH = 0x4;
  /** CType: int */
  public static final int AL_FLANGER_WAVEFORM_SINUSOID = ( 0x0 );
  /** CType: int */
  public static final int AL_ECHO_DELAY = 0x1;
  /** CType: int */
  public static final int AL_DIRECT_FILTER = 0x20005;
  /** CType: int */
  public static final int AL_QUAD32F_SOFT = 0x1206;
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_HIGH_CUTOFF = ( 4000.0f );
  /** CType: int */
  public static final int AL_REVERB_DEFAULT_DECAY_HFLIMIT = 0x1;
  /** CType: double */
  public static final double AL_ECHO_MIN_DELAY = ( 0.0 );
  /** CType: int */
  public static final int AL_SAMPLE_LENGTH_SOFT = 0x200a;
  /** CType: int */
  public static final int AL_CHORUS_PHASE = 0x2;
  /** CType: int */
  public static final int AL_FORMAT_51CHN32 = 0x120c;
  /** CType: int */
  public static final int AL_FORMAT_MONO_MULAW = 0x10014;
  /** CType: int */
  public static final int AL_EAXREVERB_GAINLF = 0x5;
  /** CType: int */
  public static final int AL_6POINT1_8_SOFT = 0x120d;
  /** CType: int */
  public static final int AL_FLANGER_WAVEFORM_TRIANGLE = ( 0x1 );
  /** CType: int */
  public static final int AL_EFFECT_ECHO = 0x4;
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_LATE_REVERB_DELAY = ( 0.011f );
  /** CType: int */
  public static final int AL_FORMAT_VORBIS_EXT = 0x10003;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_HFREFERENCE = ( 20000.0f );
  /** CType: double */
  public static final double AL_REVERB_MIN_GAINHF = ( 0.0 );
  /** CType: int */
  public static final int AL_DIRECT_CHANNELS_SOFT = 0x1033;
  /** CType: int */
  public static final int AL_STEREO_SOFT = 0x1501;
  /** CType: int */
  public static final int AL_EXT_source_distance_model = 0x1;
  /** CType: int */
  public static final int AL_RING_MODULATOR_HIGHPASS_CUTOFF = 0x2;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_WAVEFORM_SINUSOID = ( 0x0 );
  /** CType: int */
  public static final int AL_EAXREVERB_LFREFERENCE = 0x15;
  /** CType: float */
  public static final float AL_BANDPASS_DEFAULT_GAINLF = ( 1.0f );
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_AIR_ABSORPTION_GAINHF = ( 1.0f );
  /** CType: int */
  public static final int AL_MAX_DIRECT_FILTER_GAINHF_AUTO = 0x1;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_ECHO_DEPTH = ( 0.0 );
  /** CType: int */
  public static final int AL_REVERB_DECAY_HFLIMIT = 0xd;
  /** CType: int */
  public static final int AL_AUTOWAH_PEAK_GAIN = 0x4;
  /** CType: double */
  public static final double AL_REVERB_MIN_GAIN = ( 0.0 );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_GAINHF = ( 0.89f );
  /** CType: int */
  public static final int AL_FLANGER_PHASE = 0x2;
  /** CType: double */
  public static final double AL_FLANGER_MIN_DEPTH = ( 0.0 );
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_GAINLF = ( 1.0f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MIN_PHONEMEB_COARSE_TUNING = ( - 0x18 );
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_MID1_CENTER = ( 500.0f );
  /** CType: int */
  public static final int ALC_CHAN_PCM_LOKI = 0x500002;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEMEA = 0x1;
  /** CType: int */
  public static final int AL_FORMAT_QUAD8_LOKI = 0x10004;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_DENSITY = ( 1.0f );
  /** CType: int */
  public static final int AL_CONE_OUTER_GAINHF = 0x20009;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEMEB = 0x3;
  /** CType: int */
  public static final int AL_FLANGER_DEFAULT_WAVEFORM = ( 0x1 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_WAVEFORM_TRIANGLE = ( 0x1 );
  /** CType: double */
  public static final double AL_REVERB_MIN_REFLECTIONS_GAIN = ( 0.0 );
  /** CType: int */
  public static final int AL_SOFT_buffer_samples = 0x1;
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_MID2_GAIN = ( 0.126f );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_DECAY_HFRATIO = ( 0.83f );
  /** CType: int */
  public static final int AL_AUTOWAH_RESONANCE = 0x3;
  /** CType: int */
  public static final int AL_FORMAT_51CHN16 = 0x120b;
  /** CType: int */
  public static final int AL_FORMAT_QUAD8 = 0x1204;
  /** CType: float */
  public static final float AL_AUTOWAH_DEFAULT_RELEASE_TIME = ( 0.06f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MIN_PHONEMEA_COARSE_TUNING = ( - 0x18 );
  /** CType: int */
  public static final int AL_EAXREVERB_LATE_REVERB_DELAY = 0xd;
  /** CType: int */
  public static final int AL_EAXREVERB_GAINHF = 0x4;
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_FINE_TUNE = 0x2;
  /** CType: int */
  public static final int AL_FORMAT_71CHN8 = 0x1210;
  /** CType: float */
  public static final float AL_REVERB_MIN_DECAY_HFRATIO = ( 0.1f );
  /** CType: float */
  public static final float AL_CHORUS_MAX_DEPTH = ( 1.0f );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_DECAY_TIME = ( 1.49f );
  /** CType: int */
  public static final int AL_REVERB_MIN_DECAY_HFLIMIT = 0x0;
  /** CType: int */
  public static final int AL_FORMAT_71CHN16 = 0x1211;
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_AIR_ABSORPTION_GAINHF = ( 0.994f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_DEFAULT_WAVEFORM = ( 0x0 );
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_LOW_CUTOFF = ( 50.0f );
  /** CType: int */
  public static final int AL_FLOAT_SOFT = 0x1406;
  /** CType: float */
  public static final float AL_HIGHPASS_MAX_GAIN = ( 1.0f );
  /** CType: float */
  public static final float AL_CHORUS_DEFAULT_DELAY = ( 0.016f );
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_MID1_GAIN = ( 7.943f );
  /** CType: float */
  public static final float AL_DISTORTION_DEFAULT_EQBANDWIDTH = ( 3600.0f );
  /** CType: int */
  public static final int AL_SHORT_SOFT = 0x1402;
  /** CType: int */
  public static final int AL_REVERB_REFLECTIONS_GAIN = 0x7;
  /** CType: int */
  public static final int AL_EAXREVERB_REFLECTIONS_GAIN = 0x9;
  /** CType: int */
  public static final int AL_FORMAT_MONO_IMA4 = 0x1300;
  /** CType: int */
  public static final int AL_EAXREVERB_ROOM_ROLLOFF_FACTOR = 0x16;
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_ECHO_TIME = ( 0.075f );
  /** CType: float */
  public static final float AL_ECHO_DEFAULT_DAMPING = ( 0.5f );
  /** CType: int */
  public static final int AL_FLANGER_WAVEFORM = 0x1;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEMEA_COARSE_TUNING = 0x2;
  /** CType: int */
  public static final int AL_EFFECT_DISTORTION = 0x3;
  /** CType: float */
  public static final float AL_VOCAL_MORPHER_DEFAULT_RATE = ( 1.41f );
  /** CType: int */
  public static final int ALC_EFX_MINOR_VERSION = 0x20002;
  /** CType: double */
  public static final double AL_REVERB_MIN_LATE_REVERB_DELAY = ( 0.0 );
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_DECAY_LFRATIO = ( 0.1f );
  /** CType: float */
  public static final float AL_ECHO_MAX_DELAY = ( 0.207f );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_DENSITY = ( 1.0f );
  /** CType: float */
  public static final float AL_AUTOWAH_MIN_RESONANCE = ( 2.0f );
  /** CType: int */
  public static final int AL_RING_MODULATOR_WAVEFORM = 0x3;
  /** CType: int */
  public static final int AL_LOKI_IMA_ADPCM_format = 0x1;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_LFREFERENCE = ( 1000.0f );
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_MID2_CENTER = ( 1000.0f );
  /** CType: int */
  public static final int AL_DEFAULT_AUXILIARY_SEND_FILTER_GAINHF_AUTO = 0x1;
  /** CType: float */
  public static final float AL_ECHO_DEFAULT_SPREAD = ( - 1.0f );
  /** CType: int */
  public static final int ALC_BYTE_SOFT = 0x1400;
  /** CType: int */
  public static final int ALC_CONNECTED = 0x313;
  /** CType: double */
  public static final double AL_REVERB_MIN_ROOM_ROLLOFF_FACTOR = ( 0.0 );
  /** CType: int */
  public static final int AL_FLANGER_FEEDBACK = 0x5;
  /** CType: int */
  public static final int AL_EFFECTSLOT_EFFECT = 0x1;
  /** CType: float */
  public static final float AL_REVERB_MAX_REFLECTIONS_GAIN = ( 3.16f );
  /** CType: float */
  public static final float AL_ECHO_DEFAULT_DELAY = ( 0.1f );
  /** CType: int */
  public static final int AL_EAXREVERB_LATE_REVERB_PAN = 0xe;
  /** CType: int */
  public static final int AL_EAXREVERB_MAX_DECAY_HFLIMIT = 0x1;
  /** CType: int */
  public static final int AL_QUAD16_SOFT = 0x1205;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_DECAY_TIME = ( 1.49f );
  /** CType: int */
  public static final int AL_SOFT_source_latency = 0x1;
  /** CType: int */
  public static final int AL_MIN_AUXILIARY_SEND_FILTER_GAIN_AUTO = 0x0;
  /** CType: int */
  public static final int AL_SOFT_buffer_sub_data = 0x1;
  /** CType: int */
  public static final int AL_FORMAT_71CHN32 = 0x1212;
  /** CType: double */
  public static final double AL_REVERB_MIN_DIFFUSION = ( 0.0 );
  /** CType: int */
  public static final int AL_EFFECT_RING_MODULATOR = 0x9;
  /** CType: int */
  public static final int AL_REAR_SOFT = 0x1502;
  /** CType: float */
  public static final float AL_DISTORTION_MAX_EQCENTER = ( 24000.0f );
  /** CType: int */
  public static final int AL_EFFECTSLOT_NULL = 0x0;
  /** CType: int */
  public static final int AL_CHORUS_DEFAULT_WAVEFORM = ( 0x1 );
  /** CType: int */
  public static final int AL_EXT_ALAW = 0x1;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_REFLECTIONS_DELAY = ( 0.3f );
  /** CType: int */
  public static final int AL_EFFECT_FLANGER = 0x5;
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_HIGH_GAIN = ( 7.943f );
  /** CType: double */
  public static final double AL_LOWPASS_MIN_GAIN = ( 0.0 );
  /** CType: int */
  public static final int AL_DISTORTION_EQCENTER = 0x4;
  /** CType: int */
  public static final int AL_BYTE_LENGTH_SOFT = 0x2009;
  /** CType: int */
  public static final int AL_RING_MODULATOR_SQUARE = ( 0x2 );
  /** CType: int */
  public static final int AL_FILTER_BANDPASS = 0x3;
  /** CType: float */
  public static final float AL_REVERB_MIN_AIR_ABSORPTION_GAINHF = ( 0.892f );
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_LOW_GAIN = ( 0.126f );
  /** CType: int */
  public static final int AL_FLANGER_DELAY = 0x6;
  /** CType: int */
  public static final int AL_5POINT1_16_SOFT = 0x120b;
  /** CType: int */
  public static final int AL_LOWPASS_GAINHF = 0x2;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MIN_WAVEFORM = ( 0x0 );
  /** CType: int */
  public static final int AL_SOFT_direct_channels = 0x1;
  /** CType: int */
  public static final int AL_DISTORTION_LOWPASS_CUTOFF = 0x3;
  /** CType: float */
  public static final float AL_AUTOWAH_MIN_ATTACK_TIME = ( 1.0E-4f );
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_LATE_REVERB_DELAY = ( 0.0 );
  /** CType: int */
  public static final int AL_EFFECT_AUTOWAH = 0xa;
  /** CType: int */
  public static final int AL_FORMAT_REAR_MULAW = 0x10022;
  /** CType: double */
  public static final double AL_CHORUS_MIN_DEPTH = ( 0.0 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_IY = ( 0xc );
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_HIGH_GAIN = ( 0.126f );
  /** CType: int */
  public static final int AL_FLANGER_MAX_PHASE = ( 0xb4 );
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_DIFFUSION = ( 1.0f );
  /** CType: int */
  public static final int ALC_EXT_DEDICATED = 0x1;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_IH = ( 0xb );
  /** CType: float */
  public static final float AL_DISTORTION_MIN_EQBANDWIDTH = ( 80.0f );
  /** CType: int */
  public static final int AL_REAR8_SOFT = 0x1207;
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_HFREFERENCE = ( 5000.0f );
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_MIN_COARSE_TUNE = ( - 0xc );
  /** CType: int */
  public static final int AL_FORMAT_QUAD16_LOKI = 0x10005;
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_MID1_CENTER = ( 200.0f );
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_MID2_WIDTH = ( 1.0f );
  /** CType: int */
  public static final int AL_7POINT1_SOFT = 0x1506;
  /** CType: int */
  public static final int AL_UNSIGNED_BYTE3_SOFT = 0x1409;
  /** CType: int */
  public static final int AL_SOURCE_RADIUS = 0x1031;
  /** CType: int */
  public static final int AL_FORMAT_QUAD16 = 0x1205;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEMEB_COARSE_TUNING = 0x4;
  /** CType: float */
  public static final float AL_FREQUENCY_SHIFTER_MAX_FREQUENCY = ( 24000.0f );
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_FREQUENCY = 0x1;
  /** CType: float */
  public static final float AL_DISTORTION_DEFAULT_EDGE = ( 0.2f );
  /** CType: int */
  public static final int AL_MIN_DIRECT_FILTER_GAINHF_AUTO = 0x0;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_LATE_REVERB_GAIN = ( 1.26f );
  /** CType: int */
  public static final int ALC_CHAN_CD_LOKI = 0x500003;
  /** CType: int */
  public static final int AL_FLANGER_MIN_WAVEFORM = ( 0x0 );
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_LOW_CUTOFF = ( 800.0f );
  /** CType: float */
  public static final float AL_REVERB_MAX_REFLECTIONS_DELAY = ( 0.3f );
  /** CType: int */
  public static final int AL_FORMAT_STEREO_MULAW_EXT = 0x10015;
  /** CType: int */
  public static final int AL_FORMAT_MONO_DOUBLE_EXT = 0x10012;
  /** CType: float */
  public static final float AL_REVERB_MAX_AIR_ABSORPTION_GAINHF = ( 1.0f );
  /** CType: int */
  public static final int AL_DISTORTION_GAIN = 0x2;
  /** CType: int */
  public static final int AL_FLANGER_RATE = 0x3;
  /** CType: int */
  public static final int AL_COMPRESSOR_MAX_ONOFF = ( 0x1 );
  /** CType: int */
  public static final int AL_ECHO_DAMPING = 0x3;
  /** CType: int */
  public static final int ALC_EXT_disconnect = 0x1;
  /** CType: int */
  public static final int AL_CHORUS_DELAY = 0x6;
  /** CType: int */
  public static final int AL_FORMAT_MONO_FLOAT32 = 0x10010;
  /** CType: float */
  public static final float AL_AUTOWAH_DEFAULT_RESONANCE = ( 1000.0f );
  /** CType: float */
  public static final float AL_CHORUS_MIN_FEEDBACK = ( - 1.0f );
  /** CType: int */
  public static final int AL_EQUALIZER_MID2_WIDTH = 0x8;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_LATE_REVERB_GAIN = ( 0.0 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_RATE = 0x6;
  /** CType: float */
  public static final float AL_REVERB_MAX_DECAY_TIME = ( 20.0f );
  /** CType: int */
  public static final int AL_6POINT1_32F_SOFT = 0x120f;
  /** CType: int */
  public static final int AL_FORMAT_REAR16 = 0x1208;
  /** CType: double */
  public static final double AL_LOWPASS_MIN_GAINHF = ( 0.0 );
  /** CType: float */
  public static final float AL_DISTORTION_DEFAULT_EQCENTER = ( 3600.0f );
  /** CType: int */
  public static final int AL_FORMAT_MONO_MULAW_EXT = 0x10014;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_ROOM_ROLLOFF_FACTOR = ( 10.0f );
  /** CType: int */
  public static final int AL_EXT_MCFORMATS = 0x1;
  /** CType: int */
  public static final int AL_EFFECT_LAST_PARAMETER = 0x8000;
  /** CType: float */
  public static final float AL_RING_MODULATOR_DEFAULT_FREQUENCY = ( 440.0f );
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_LOW_GAIN = ( 7.943f );
  /** CType: int */
  public static final int AL_EAXREVERB_DECAY_HFRATIO = 0x7;
  /** CType: int */
  public static final int AL_EAXREVERB_DECAY_HFLIMIT = 0x17;
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_HIGH_GAIN = ( 1.0f );
  /** CType: int */
  public static final int AL_STEREO16_SOFT = 0x1103;
  /** CType: float */
  public static final float AL_ECHO_MAX_FEEDBACK = ( 1.0f );
  /** CType: float */
  public static final float AL_LOWPASS_DEFAULT_GAIN = ( 1.0f );
  /** CType: int */
  public static final int AL_EXT_STATIC_BUFFER = 0x1;
  /** CType: double */
  public static final double AL_BANDPASS_MIN_GAIN = ( 0.0 );
  /** CType: double */
  public static final double AL_DEFAULT_ROOM_ROLLOFF_FACTOR = ( 0.0 );
  /** CType: int */
  public static final int AL_FORMAT_61CHN_MULAW = 0x10024;
  /** CType: float */
  public static final float AL_ECHO_DEFAULT_FEEDBACK = ( 0.5f );
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_LEFT_DIRECTION = 0x2;
  /** CType: int */
  public static final int AL_DISTORTION_EDGE = 0x1;
  /** CType: int */
  public static final int AL_FORMAT_71CHN_MULAW = 0x10025;
  /** CType: int */
  public static final int ALC_FORMAT_CHANNELS_SOFT = 0x1990;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_REFLECTIONS_DELAY = ( 0.0 );
  /** CType: int */
  public static final int ALC_EFX_MAJOR_VERSION = 0x20001;
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_MID1_GAIN = ( 0.126f );
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_MID1_CENTER = ( 3000.0f );
  /** CType: int */
  public static final int AL_EFFECT_TYPE = 0x8001;
  /** CType: float */
  public static final float AL_REVERB_MAX_DENSITY = ( 1.0f );
  /** CType: int */
  public static final int AL_ROOM_ROLLOFF_FACTOR = 0x20008;
  /** CType: double */
  public static final double AL_EAXREVERB_DEFAULT_LATE_REVERB_PAN_XYZ = ( 0.0 );
  /** CType: double */
  public static final double AL_RING_MODULATOR_MIN_FREQUENCY = ( 0.0 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_EH = ( 0x9 );
  /** CType: float */
  public static final float AL_RING_MODULATOR_MAX_HIGHPASS_CUTOFF = ( 24000.0f );
  /** CType: int */
  public static final int AL_FORMAT_REAR32 = 0x1209;
  /** CType: int */
  public static final int ALC_INT_SOFT = 0x1404;
  /** CType: double */
  public static final double AL_DISTORTION_MIN_EDGE = ( 0.0 );
  /** CType: int */
  public static final int AL_RING_MODULATOR_MAX_WAVEFORM = ( 0x2 );
  /** CType: int */
  public static final int AL_FORMAT_STEREO_ALAW_EXT = 0x10017;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_ER = ( 0xa );
  /** CType: int */
  public static final int AL_CHORUS_DEFAULT_PHASE = ( 0x5a );
  /** CType: int */
  public static final int AL_FLANGER_DEFAULT_PHASE = ( 0x0 );
  /** CType: int */
  public static final int AL_EAXREVERB_DECAY_TIME = 0x6;
  /** CType: float */
  public static final float AL_EQUALIZER_DEFAULT_LOW_CUTOFF = ( 200.0f );
  /** CType: float */
  public static final float AL_DISTORTION_MAX_GAIN = ( 1.0f );
  /** CType: int */
  public static final int AL_7POINT1_32F_SOFT = 0x1212;
  /** CType: float */
  public static final float AL_ECHO_DEFAULT_LRDELAY = ( 0.1f );
  /** CType: int */
  public static final int AL_EFFECT_VOCAL_MORPHER = 0x7;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_AIR_ABSORPTION_GAINHF = ( 0.994f );
  /** CType: int */
  public static final int AL_RING_MODULATOR_DEFAULT_WAVEFORM = ( 0x0 );
  /** CType: int */
  public static final int AL_COMPRESSOR_MIN_ONOFF = ( 0x0 );
  /** CType: int */
  public static final int AL_EAXREVERB_HFREFERENCE = 0x14;
  /** CType: int */
  public static final int AL_EAXREVERB_REFLECTIONS_PAN = 0xb;
  /** CType: double */
  public static final double AL_REVERB_DEFAULT_ROOM_ROLLOFF_FACTOR = ( 0.0 );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_MODULATION_TIME = ( 0.25f );
  /** CType: int */
  public static final int AL_UNSIGNED_SHORT_SOFT = 0x1403;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_ECHO_DEPTH = ( 1.0f );
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_DECAY_HFRATIO = ( 0.1f );
  /** CType: double */
  public static final double AL_EAXREVERB_DEFAULT_ROOM_ROLLOFF_FACTOR = ( 0.0 );
  /** CType: double */
  public static final double AL_BANDPASS_MIN_GAINHF = ( 0.0 );
  /** CType: double */
  public static final double AL_ECHO_MIN_LRDELAY = ( 0.0 );
  /** CType: double */
  public static final double AL_EAXREVERB_DEFAULT_ECHO_DEPTH = ( 0.0 );
  /** CType: double */
  public static final double AL_VOCAL_MORPHER_MIN_RATE = ( 0.0 );
  /** CType: float */
  public static final float AL_CHORUS_DEFAULT_DEPTH = ( 0.1f );
  /** CType: int */
  public static final int AL_STEREO32F_SOFT = 0x10011;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_ROOM_ROLLOFF_FACTOR = ( 0.0 );
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_MIN_FINE_TUNE = ( - 0x32 );
  /** CType: float */
  public static final float AL_EAXREVERB_DEFAULT_LATE_REVERB_GAIN = ( 1.26f );
  /** CType: int */
  public static final int AL_EFFECT_PITCH_SHIFTER = 0x8;
  /** CType: int */
  public static final int AL_CHORUS_WAVEFORM_SINUSOID = ( 0x0 );
  /** CType: int */
  public static final int AL_FORMAT_QUAD_MULAW = 0x10021;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_REFLECTIONS_GAIN = ( 3.16f );
  /** CType: float */
  public static final float AL_BANDPASS_DEFAULT_GAIN = ( 1.0f );
  /** CType: int */
  public static final int AL_EQUALIZER_MID1_CENTER = 0x4;
  /** CType: int */
  public static final int AL_BANDPASS_GAINHF = 0x3;
  /** CType: int */
  public static final int AL_INT_SOFT = 0x1404;
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_MAX_RIGHT_DIRECTION = ( 0x2 );
  /** CType: int */
  public static final int AL_FORMAT_51CHN_MULAW = 0x10023;
  /** CType: int */
  public static final int AL_AUXILIARY_SEND_FILTER = 0x20006;
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_MAX_LEFT_DIRECTION = ( 0x2 );
  /** CType: int */
  public static final int AL_QUAD_SOFT = 0x1503;
  /** CType: int */
  public static final int AL_EAXREVERB_REFLECTIONS_DELAY = 0xa;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_Z = ( 0x1d );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_U = ( 0x4 );
  /** CType: int */
  public static final int ALC_FORMAT_TYPE_SOFT = 0x1991;
  /** CType: float */
  public static final float AL_REVERB_MAX_GAIN = ( 1.0f );
  /** CType: float */
  public static final float AL_REVERB_MAX_LATE_REVERB_GAIN = ( 10.0f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_V = ( 0x1c );
  /** CType: int */
  public static final int AL_BANDPASS_GAINLF = 0x2;
  /** CType: double */
  public static final double AL_ECHO_MIN_FEEDBACK = ( 0.0 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_R = ( 0x19 );
  /** CType: int */
  public static final int ALC_EXT_EFX = 0x1;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_S = ( 0x1a );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_T = ( 0x1b );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_M = ( 0x16 );
  /** CType: int */
  public static final int ALC_5POINT1_SOFT = 0x1504;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_N = ( 0x17 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_O = ( 0x3 );
  /** CType: int */
  public static final int AL_EAXREVERB_DIFFUSION = 0x2;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_P = ( 0x18 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_I = ( 0x2 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_J = ( 0x13 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_K = ( 0x14 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_L = ( 0x15 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_E = ( 0x1 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_F = ( 0x11 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_G = ( 0x12 );
  /** CType: float */
  public static final float AL_AUTOWAH_MIN_RELEASE_TIME = ( 1.0E-4f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_A = ( 0x0 );
  /** CType: int */
  public static final int AL_CHORUS_RATE = 0x3;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_B = ( 0xf );
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_COARSE_TUNE = 0x1;
  /** CType: float */
  public static final float AL_FLANGER_DEFAULT_DELAY = ( 0.002f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_D = ( 0x10 );
  /** CType: int */
  public static final int AL_BYTE3_SOFT = 0x1408;
  /** CType: int */
  public static final int AL_MONO8_SOFT = 0x1100;
  /** CType: float */
  public static final float AL_REVERB_DEFAULT_REFLECTIONS_DELAY = ( 0.007f );
  /** CType: float */
  public static final float AL_EAXREVERB_MIN_HFREFERENCE = ( 1000.0f );
  /** CType: float */
  public static final float AL_EQUALIZER_MIN_MID2_WIDTH = ( 0.01f );
  /** CType: int */
  public static final int AL_ECHO_FEEDBACK = 0x4;
  /** CType: int */
  public static final int AL_PITCH_SHIFTER_DEFAULT_FINE_TUNE = ( 0x0 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_AE = ( 0x6 );
  /** CType: double */
  public static final double AL_MIN_CONE_OUTER_GAINHF = ( 0.0 );
  /** CType: int */
  public static final int ALC_UNSIGNED_BYTE_SOFT = 0x1401;
  /** CType: int */
  public static final int AL_FLANGER_MAX_WAVEFORM = ( 0x1 );
  /** CType: int */
  public static final int AL_FILTER_FIRST_PARAMETER = 0x0;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_AA = ( 0x5 );
  /** CType: int */
  public static final int AL_EQUALIZER_LOW_CUTOFF = 0x2;
  /** CType: int */
  public static final int AL_RING_MODULATOR_FREQUENCY = 0x1;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_AO = ( 0x8 );
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_GAINHF = ( 0.0 );
  /** CType: float */
  public static final float AL_FLANGER_MIN_FEEDBACK = ( - 1.0f );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_PHONEME_AH = ( 0x7 );
  /** CType: int */
  public static final int ALC_SHORT_SOFT = 0x1402;
  /** CType: float */
  public static final float AL_HIGHPASS_DEFAULT_GAIN = ( 1.0f );
  /** CType: float */
  public static final float AL_FLANGER_MAX_DELAY = ( 0.004f );
  /** CType: double */
  public static final double AL_FREQUENCY_SHIFTER_DEFAULT_FREQUENCY = ( 0.0 );
  /** CType: int */
  public static final int AL_LOKI_WAVE_format = 0x1;
  /** CType: int */
  public static final int AL_FREQUENCY_SHIFTER_DIRECTION_UP = ( 0x1 );
  /** CType: int */
  public static final int AL_DISTORTION_EQBANDWIDTH = 0x5;
  /** CType: int */
  public static final int AL_EQUALIZER_HIGH_GAIN = 0x9;
  /** CType: double */
  public static final double AL_BANDPASS_MIN_GAINLF = ( 0.0 );
  /** CType: float */
  public static final float AL_REVERB_MAX_LATE_REVERB_DELAY = ( 0.1f );
  /** CType: int */
  public static final int ALC_FLOAT_SOFT = 0x1406;
  /** CType: float */
  public static final float AL_DISTORTION_MAX_LOWPASS_CUTOFF = ( 24000.0f );
  /** CType: int */
  public static final int AL_DEFAULT_AUXILIARY_SEND_FILTER_GAIN_AUTO = 0x1;
  /** CType: int */
  public static final int ALC_MAX_AUXILIARY_SENDS = 0x20003;
  /** CType: int */
  public static final int AL_ECHO_SPREAD = 0x5;
  /** CType: float */
  public static final float AL_EQUALIZER_MAX_MID2_CENTER = ( 8000.0f );
  /** CType: int */
  public static final int AL_DEDICATED_GAIN = 0x1;
  /** CType: float */
  public static final float AL_EAXREVERB_MAX_DENSITY = ( 1.0f );
  /** CType: int */
  public static final int AL_EAXREVERB_MIN_DECAY_HFLIMIT = 0x0;
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MAX_PHONEMEB = ( 0x1d );
  /** CType: int */
  public static final int AL_FILTER_NULL = 0x0;
  /** CType: double */
  public static final double AL_EAXREVERB_MIN_MODULATION_DEPTH = ( 0.0 );
  /** CType: int */
  public static final int AL_VOCAL_MORPHER_MAX_PHONEMEA = ( 0x1d );
  /** CType: float */
  public static final float AL_CHORUS_MAX_FEEDBACK = ( 1.0f );
  /** CType: double */
  public static final double AL_REVERB_MIN_LATE_REVERB_GAIN = ( 0.0 );
  /** CType: int */
  public static final int AL_6POINT1_SOFT = 0x1505;
  /** CType: int */
  public static final int AL_REVERB_REFLECTIONS_DELAY = 0x8;
  /** CType: float */
  public static final float AL_CHORUS_MAX_RATE = ( 10.0f );


} // end of class ALExtConstants
